apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
  - name: redis-wal
    uid: redis-wal
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    jsonData:
      dbIndex: 0
      client: standalone
