apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true

  - name: redis-meta
    uid: redis-meta
    type: redis-datasource
    access: proxy
    url: redis://redis-meta:6379
    jsonData:
      client: standalone
      dbIndex: 0

  - name: redis-data
    uid: redis-data
    type: redis-datasource
    access: proxy
    url: redis://redis-data:6379
    jsonData:
      client: standalone
      dbIndex: 0