services:
  otel:
    image: grafana/otel-lgtm:latest
    container_name: otel-lgtm
    restart: unless-stopped
    ports:
      - "4317:4317" # OTLP gRPC -- exposed to svcs only
      - "4318:4318" # OTLP HTTP -- exposed to svcs only
      - "3000:3000" # LGTM UI -- accessible to everyone
    environment:
      - LOG_LEVEL=info
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/grid-scale.json
      - ENABLE_LOGS_TEMPO=true
    volumes:
      - ./data/otel/:/data/ # attach the PV here (paths inside docker)
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/grid-scale-1772977878374.json:/etc/grafana/provisioning/dashboards/grid-scale.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-meta:
    image: redis:7-alpine
    mem_limit: 1g
    cpus: "1.0"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  redis-data:
    image: redis:7-alpine
    mem_limit: 1g
    cpus: "1.0"
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  rest-wrapper:
    build:
      context: ../
      dockerfile: ./api-tests/rest-wrapper/dockerfile
    mem_limit: 512m
    cpus: "1.0"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      REDIS_META_CONNECTION_STRING: redis://redis-meta:6379
      REDIS_DATA_CONNECTION_STRING: redis://redis-data:6379
      TIME_TOLERANCE_IN_MS: "60000" # 1 minute
      TIME_WINDOW_IN_MS: "1200000" # 20 minutes
      SIZE_WINDOW_IN_BYTES: "314572800" # 300mb
      MAX_PAGES_IN_BOOK: "3"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel:4318
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_SERVICE_NAME: rest-wrapper
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health/liveliness" ]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      redis-meta:
        condition: service_healthy
      otel:
        condition: service_healthy
  checkpointer:
    build:
      context: ../
      dockerfile: ./api-tests/hdfs-sqlite-checkpointer/dockerfile
    mem_limit: 2GB
    cpus: "1.0"
    ports:
      - "8082:8080"
      - "8083:8081"
    environment:
      REDIS_META_CONNECTION_STRING: redis://redis-meta:6379
      REDIS_DATA_CONNECTION_STRING: redis://redis-data:6379
      TIME_TOLERANCE_IN_MS: "60000"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel:4318
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_SERVICE_NAME: hdfs-sqlite-checkpointer
      TEMP_CHECKPOINTING_PATH: /checkpoints
    volumes:
      - ./data/checkpoints:/checkpoints
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health/liveliness" ]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      rest-wrapper:
        condition: service_healthy
      redis-meta:
        condition: service_healthy
      otel:
        condition: service_healthy

networks:
  default:
    name: grid-store-network
