services:
  k6-single:
    image: grafana/k6:latest
    deploy:
      replicas: 1
    volumes:
      - ../dist/api-tests/seq-single-write-range-read-tests.js:/scripts/seq-single-write-range-read-tests.js:ro
    environment:
      TEST_URL: http://rest-wrapper:8080
      SCRIPT_VUS: "100"
      SCRIPT_ITERATIONS: "50000"
      SCRIPT_MAX_DURATION: 30m
      SLEEP_DURATION: "1"
      K6_OTEL_GRPC_EXPORTER_INSECURE: "true"
      K6_OTEL_METRIC_PREFIX: "k6_"
      K6_OTEL_GRPC_EXPORTER_ENDPOINT: "otel:4317"
    command:
      - run
      - --out
      - opentelemetry
      - /scripts/seq-single-write-range-read-tests.js
  k6-bulk-time:
    image: grafana/k6:latest
    deploy:
      replicas: 1
    volumes:
      - ../dist/api-tests/seq-bulk-time-write-range-read-tests.js:/scripts/seq-bulk-time-write-range-read-tests.js:ro
    environment:
      TEST_URL: http://rest-wrapper:8080
      SCRIPT_VUS: "100"
      SCRIPT_ITERATIONS: "50000"
      SCRIPT_MAX_DURATION: 30m
      SLEEP_DURATION: "1"
      BULK: "100"
      K6_OTEL_GRPC_EXPORTER_INSECURE: "true"
      K6_OTEL_METRIC_PREFIX: "k6_"
      K6_OTEL_GRPC_EXPORTER_ENDPOINT: "otel:4317"
    command:
      - run
      - --out
      - opentelemetry
      - /scripts/seq-bulk-time-write-range-read-tests.js
  k6-bulk-tag:
    image: grafana/k6:latest
    deploy:
      replicas: 1
    volumes:
      - ../dist/api-tests/seq-bulk-tag-write-range-read-tests.js:/scripts/seq-bulk-tag-write-range-read-tests.js:ro
    environment:
      TEST_URL: http://rest-wrapper:8080
      SCRIPT_VUS: "100"
      SCRIPT_ITERATIONS: "50000"
      SCRIPT_MAX_DURATION: 30m
      SLEEP_DURATION: "1"
      BULK: "100"
      K6_OTEL_GRPC_EXPORTER_INSECURE: "true"
      K6_OTEL_METRIC_PREFIX: "k6_"
      K6_OTEL_GRPC_EXPORTER_ENDPOINT: "otel:4317"
    command:
      - run
      - --out
      - opentelemetry
      - /scripts/seq-bulk-tag-write-range-read-tests.js
networks:
  default:
    name: grid-store-network
