FROM node:lts-slim
RUN apt-get update && apt-get install -y curl
WORKDIR /app/dist
COPY dist/package.json ./package.json
RUN npm install
COPY dist /app/dist/
#Application listens on 8080 for API requests
EXPOSE 8080
#Application listens on 8081 for diagnostics/health requests
EXPOSE 8081
USER node
CMD ["node", "--loader=@opentelemetry/instrumentation/hook.mjs", "--import", "./api-tests/rest-wrapper/otel-instrumentation.js", "./api-tests/rest-wrapper/rest-wrapper.js"]